# Path
export PATH="usr/local/bin:usr/local/sbin:$PATH"

export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

# Plugins
zplug "plugins/brew", from:oh-my-zsh
zplug "plugins/httpie", from:oh-my-zsh
zplug "atweiden/fzf-extras", use:fzf-extras.sh
zplug "b4b4r07/enhancd", use:init.sh
zplug "plugins/osx", from:oh-my-zsh
zplug "zsh-users/zsh-autosuggestions"
zplug "lukechilds/zsh-nvm"
zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-syntax-highlighting"
zplug "themes/kolo", from:oh-my-zsh

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
	printf "Install? [y/N]: "
	if read -q; then
		echo; zplug install
	fi
fi

# Then, source plugins and add commands to $PATH
zplug load

# Load config files
for zsh_source in ~/.dotfiles/zsh/configs/*.zsh; do
	source $zsh_source
done

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
